### ISSUE TITLE
Install fails with new SQLite Version

### ISSUE THREAD

**Issue by monprin** [rogerbinns/apsw#223]
I tried installing apsw this morning and get an error (included at end). sqlite 3.6.0 was also released today and given the error, it seems to be related. I am on an Ubuntu 16.04 machine. If you need any other debug info I can provide. I will also be looking into this more.

Error:
```
(camoco) jeffe174@helix19:/project/csbio/jeffe174/.local/apsw$ python setup.py fetch --missing-checksum-ok --all build --enable-all-extensions install
/project/csbio/jeffe174/.local/conda/envs/camoco/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/dist.py:331: UserWarning: Normalizing '3.15.2-r1' to '3.15.2.post1'
running fetch
  Getting download page to work out current SQLite version
    Fetching https://sqlite.org/download.html
    Version is 3.16.0
  Getting the SQLite amalgamation
    Fetching https://sqlite.org/2016/sqlite-autoconf-3160000.tar.gz
    Length: 3710  SHA1: 604332cc8f6eeb518ffdc9e1d38c38bb8df71549  MD5: 910d4a575f26b56f8dd97a881e1b9e95
    (Not verified.  No match in checksums file)
Traceback (most recent call last):
  File "setup.py", line 894, in <module>
    'win64hackvars': win64hackvars}
  File "/project/csbio/jeffe174/.local/conda/envs/camoco/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/project/csbio/jeffe174/.local/conda/envs/camoco/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/project/csbio/jeffe174/.local/conda/envs/camoco/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 328, in run
    tar=tarfile.open("nonexistentname to keep old python happy", 'r', data)
  File "/project/csbio/jeffe174/.local/conda/envs/camoco/lib/python3.5/tarfile.py", line 1562, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by rogerbinns** [comment]
You are a victim of several things:

* APSW hasn't been updated for 3.16.0 yet
* SQLite uses years in the URL - you'll need to temporarily update [this code](https://github.com/rogerbinns/apsw/blob/master/setup.py#L74)
* The SQLite website doesn't do HTTP properly so instead of a 404, you get 302 leaving the client thinking the url is correct and then trying to use the result content which isn't sqlite.

In any event I am closing this, since it will be fixed as part of the next APSW release.
