### ISSUE TITLE
deprecated buffer protocol API

### ISSUE THREAD

**Issue by dfateyev** [rogerbinns/apsw#301]
python-apsw fails to build with Python 3.10.0a2.

```
Traceback (most recent call last):
  File "/builddir/build/BUILD/apsw-3.33.0-r1/setup.py", line 907, in <module>
    setup(name="apsw",
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/builddir/build/BUILD/apsw-3.33.0-r1/setup.py", line 130, in run
    import tests
  File "/builddir/build/BUILD/apsw-3.33.0-r1/tests.py", line 9, in <module>
    import apsw
ImportError: /builddir/build/BUILDROOT/python-apsw-3.33.0.r1-1.fc34.x86_64/usr/lib64/python3.10/site-packages/apsw.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyObject_AsWriteBuffer
```
https://docs.python.org/3.10/whatsnew/changelog.html#id16

`bpo-41103: PyObject_AsCharBuffer(), PyObject_AsReadBuffer(), PyObject_CheckReadBuffer(), and PyObject_AsWriteBuffer() are removed. Please migrate to new buffer protocol; PyObject_GetBuffer() and PyBuffer_Release().`

**Comment by rogerbinns** [comment]
Done in 3.35.4-r1
