### ISSUE TITLE
AttributeError: module 'apsw' has no attribute 'sqlitelibversion' always occurs under exe execution after nuitka build

### ISSUE THREAD

**Issue by kelvinwang139** [rogerbinns/apsw#399]
Hi,
thansk for your supports in advance!
 
I use nuitka tool to convert my python project(than use peewee with aspw) to exe and run the exe and the issue always occured as below:

D:\workspace\ai\ai-desktop\cyai\out\start.dist>D:\workspace\ai\ai-desktop\cyai\out\ok\start.exe
Traceback (most recent call last):
  File "D:\WORKSP~1\ai\AI-DES~1\cyai\out\ok\start.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\WORKSP~1\ai\AI-DES~1\cyai\out\ok\main_window.py", line 9, in <module main_window>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\WORKSP~1\ai\AI-DES~1\cyai\out\ok\db\service.py", line 10, in <module db.service>
    from playhouse.apsw_ext import APSWDatabase
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\WORKSP~1\ai\AI-DES~1\cyai\out\ok\playhouse\apsw_ext.py", line 33, in <module playhouse.apsw_ext>
    class APSWDatabase(SqliteExtDatabase):
  File "D:\WORKSP~1\ai\AI-DES~1\cyai\out\ok\playhouse\apsw_ext.py", line 34, in APSWDatabase
    server_version = tuple(int(i) for i in apsw.sqlitelibversion().split('.'))
AttributeError: module 'apsw' has no attribute 'sqlitelibversion'

could you please provide some solution?

**Comment by rogerbinns** [comment]
It is an issue with nuitka which I have reported at https://github.com/Nuitka/Nuitka/issues/2039

**Comment by rogerbinns** [comment]
It is an issue in nuitka and has been tagged to be fixed in a future version.  There is a short term workaround.

Find the main apsw dll:

    python -c "import apsw; print(apsw.__file__)"

For Windows 64 bit Python 3.10 it will be a filename something like:

    \wherever\packages\are\installed\apsw\__init__.cp310-win_amd64.pyd

Copy the file somewhere your Python can access, replacing the ````__init__```` with ````apsw```` in the filename.  For example the above would end up being:

    apsw.cp310-win_amd64.pyd

Check this file is picked up:

    python -c "import apsw; print(apsw.__file__)"

Once that is the case your nuitka builds will work.

**Comment by kelvinwang139** [comment]
Thanks a loy
