### ISSUE TITLE
Custom VFS + WAL = odd behavior

### ISSUE THREAD

**Issue by Nikratio** [rogerbinns/apsw#423]
Hi Roger,

I somewhat complex issue, but I managed to break it down to a simple test script. In short, in some specific circumstances (WAL + custom VFS + something about the database itself) I am getting SQLITE_CANTOPEN errors.

Due to the involvement of WAL and custom VFS, I suspect this is related to apsw rather than SQLite.. but I may be wrong.

Here's the problem:

```
$ ./test.py create
creating table
$ ./test.py
3.34.0-r1
reading table
```

works fine.

But if we use a slightly different table, we get the unexpected error:

```
$ cp test.db.bak test.db
$ ./test.py 
3.34.0-r1
Traceback (most recent call last):
  File "/home/nikratio/in-progress/s3ql/./test.py", line 53, in <module>
    conn = get_conn()
  File "/home/nikratio/in-progress/s3ql/./test.py", line 48, in get_conn
    cur.execute(s)
apsw.CantOpenError: CantOpenError: unable to open database file
```

If you disable the use of the custom VFS, it works.

Any thoughts?
[testcase.zip](https://github.com/rogerbinns/apsw/files/11094555/testcase.zip)

**Comment by rogerbinns** [comment]
I am unable to reproduce the error, using either current APSW and current SQLite, or APSW and SQLite 3.34.0.

One gotcha I do see in the script is only `test.db` is unlinked, whereas it should unlink `test.db*`.  If you have leftover `-wal` or  `-shm` from prior runs, combined with a new `test.db` I suspect weird issues would result.

**Comment by Nikratio** [comment]
Thanks for checking!

No, there are no leftover WAL files. 

I was also unable to reproduce this on a fresh Debian VM with most recent APSW, and Pypi's apsw on my development machine does not trigger the problem either:

```
nikratio@vostro ~/i/s3ql (next)> rm -f test.db-*; cp test.db.bak test.db
fish: No matches for wildcard “test.db-*”. See `help expand`.
rm -f test.db-*; cp test.db.bak test.db
      ^
nikratio@vostro ~/i/s3ql (next)> ./test.py
3.34.0-r1
3.34.1
Traceback (most recent call last):
  File "/home/nikratio/in-progress/s3ql/./test.py", line 54, in <module>
    conn = get_conn()
  File "/home/nikratio/in-progress/s3ql/./test.py", line 48, in get_conn
    cur.execute(s)
apsw.CantOpenError: CantOpenError: unable to open database file
```

Very curious. I understand if you don't want to look into this further though.

**Comment by rogerbinns** [comment]
Unfortunately not much I can do without some way of reproducing.  

SQLite gives the can't open error for anything going wrong during the open processing.  Did you try [SQLite's logging](https://rogerbinns.github.io/apsw/apsw.html#apsw.config)?

You can use [ltrace](https://www.man7.org/linux/man-pages/man1/ltrace.1.html) to see what is happening at the library level which may help.

**Comment by rogerbinns** [comment]
@Nikratio did you get anything back from SQLite's logging, or get a reproducer?

**Comment by Nikratio** [comment]
I encountered even more problems (Python segfaulting in CI environment) so I followed your recommendation and implemented the VFS in C instead.

If you're interested in getting to the bottom of this, I can enable logging for the testcase above. Will get back to you tomorrow.

**Comment by rogerbinns** [comment]
I've been working on #425 recently which was tickled by VFS and inheritance where SQLite calls APSW which calls SQLite until the C call stack is exhausted, and you get a very confusing segfault.  There are no messages from SQLite's logging.  It is almost certain the segfault you are getting is from something like that.  If that is the case then this can be closed.

If instead it is a different bug in APSW then I do want to find and fix it, and will need some sort of reproducer.

**Comment by Nikratio** [comment]
It still happens for me with apsw 3.34.0-1, but not with 3.41.2.0. SQlite logging does not help much:

```
nikratio@vostro ~/t/apsw-bug> ./test.py
3.34.0-r1
sqlite3 says: unable to open database file in "PRAGMA journal_mode = WAL" (SQLITE_CANTOPEN)
Traceback (most recent call last):
  File "/home/nikratio/tmp/apsw-bug/./test.py", line 62, in <module>
    conn = get_conn()
  File "/home/nikratio/tmp/apsw-bug/./test.py", line 57, in get_conn
    cur.execute(s)
apsw.CantOpenError: CantOpenError: unable to open database file
[testcase.zip](https://github.com/rogerbinns/apsw/files/11149750/testcase.zip)
```

**Comment by rogerbinns** [comment]
I did version chasing and figured out the root cause using your testcase - thanks.

The CantOpenError is because the database is in WAL mode which means the VFS has to support WAL.  If you use APSW before version [3.36.0-r1](https://github.com/rogerbinns/apsw/releases/tag/3.36.0-r1) then APSW implemented VFS do not support WAL.  Supporting WAL was added in 3.36.0-r1 as #311.  This all makes sense.

I couldn't cause any crashing behaviour.

**Comment by Nikratio** [comment]
Interesting.. but why does it not happen when creating a fresh database? (See instructions at the top)

**Comment by rogerbinns** [comment]
With current SQLite it won't change the db mode to `WAL` if the VFS doesn't support the xShm methods.  Running the create step still results in a `delete` mode database.  I'm guessing that SQLite changed that at some point in the last few years.  (Verified by modifying the APSW code to set `iVersion`.)

So best guess is that older SQLite would change an open database to `WAL` mode, and then cope with missing xShm methods.  But on opening the database fresh, the missing xShm methods then results in the CantOpenError.

Note that you ran the various pragmas before putting any content in the database.  SQLite usually just has a zero length file until any content is added.

**Comment by rogerbinns** [comment]
I tested the above hypothesis and SQLite/APSW 3.34 also won't change the mode to WAL in the create step.  It is going to be something like that, but in any event this is no longer an issue with current SQLite or APSW.  Closing since there isn't much more we can do.

**Comment by Nikratio** [comment]
I don't follow your explanation. The journal mode is not a property of the database file but of the Connection that's used to open the database. So when opening one file in WAL mode it fails because the VFS does not have the xShm* methods, while when opening another file in WAL mode it succeeds because..?

```
nikratio@vostro ~/t/apsw-bug> cp test.db.working test.db && ./test.py 
3.34.0-r1
reading table
nikratio@vostro ~/t/apsw-bug> cp test.db.broken test.db && ./test.py
3.34.0-r1
sqlite3 says: unable to open database file in "PRAGMA journal_mode = WAL" (SQLITE_CANTOPEN)
Traceback (most recent call last):
  File "/home/nikratio/tmp/apsw-bug/./test.py", line 62, in <module>
    conn = get_conn()
  File "/home/nikratio/tmp/apsw-bug/./test.py", line 57, in get_conn
    cur.execute(s)
apsw.CantOpenError: CantOpenError: unable to open database file
[testcase.zip](https://github.com/rogerbinns/apsw/files/11153226/testcase.zip)

```

**Comment by Nikratio** [comment]
If you're interested in taking a look at the segfault, the CI logs are at https://github.com/s3ql/s3ql/actions/runs/4558090215/jobs/8040556004.

The test that fails the crash is pretty simple: https://github.com/s3ql/s3ql/blob/3a6962d86098c295f7c86eaccf0fa52525f2c7df/tests/t1_database.py

The VFS implementation is here: https://github.com/s3ql/s3ql/blob/3a6962d86098c295f7c86eaccf0fa52525f2c7df/src/s3ql/database.py

**Comment by rogerbinns** [comment]
> The journal mode is not a property of the database

It is entirely a property of the database.  [Bytes 18 and 19 of the file header](https://www.sqlite.org/fileformat.html#file_format_version_numbers) encode the mode, and [it is persistent](https://www.sqlite.org/wal.html#persistence_of_wal_mode)..

**Comment by rogerbinns** [comment]
Exit code 134 is SIGABRT, usually from a call to `abort()`.  The test it is happening in is test_upload_download, which I can run till `upload_metadata` because I can't find the `local` backend it wants.  However it looks like upload/download metadata are only doing file operations so they don't matter.

I ran under valgrind with Python 3.8 and 3.10 with a fresh compiled 3.34.0-r1 of APSW, as well as using Ubuntu 22.10 python3-apsw package as the CI runner is using.

There were no issues at all, and definitely no crashes.

I did [find this](https://gist.github.com/kudaba/53f68340bd28cd1e8824ac1e6ba8cf88) about how to save the Github runner core dumps.

**Comment by rogerbinns** [comment]
The runner says s3ql was at rev 3a6962d86098c295f7c86eaccf0fa52525f2c7df but on doing a git clone I can't find that revision at all!

**Comment by Nikratio** [comment]
> > The journal mode is not a property of the database
> 
> It is entirely a property of the database. [Bytes 18 and 19 of the file header](https://www.sqlite.org/fileformat.html#file_format_version_numbers) encode the mode, and [it is persistent](https://www.sqlite.org/wal.html#persistence_of_wal_mode)..

Oh, thanks! That explains a lot. So when WAL is unsupported, SQLite will return an error when trying to open a file that already has WAL enabled, but will simply do nothing when attempting to switch from Journal to WAL. I somehow expect the PRAGMA command to fail in that situation. I've now added a check of the return value, and everything makes a lot more sense :-).

**Comment by Nikratio** [comment]
> The runner says s3ql was at rev 3a6962d86098c295f7c86eaccf0fa52525f2c7df but on doing a git clone I can't find that revision at all!

That's probably because that pull request was never merged (because of the crash), and is therefore not pulled. I have just recreated that state in a new branch, you should be able to pull this: https://github.com/s3ql/s3ql/pull/284

**Comment by rogerbinns** [comment]
On a regular Ubuntu workstation I got everything pulled, and followed the same CI steps doing the cython and build_ext, but there is no crash.  The tests continue to the end.  I also tried running under valgrind which made no difference.

This isn't an identical environment as what the workflow does, but should be substantially similar.  Sadly [act](https://github.com/nektos/act) doesn't support podman so this is turning into too much yak shaving.  Giving up.
