### ISSUE TITLE
Test failure with Python 3.12.0b1

### ISSUE THREAD

**Issue by mgorny** [rogerbinns/apsw#450]
At a first glance, it's only a matter of different exception being thrown.

```
$ make test
env python3 setup.py fetch --version=3.42.0 --all build_ext -DSQLITE_ENABLE_COLUMN_METADATA --inplace --force --enable-all-extensions
running fetch
  Getting the SQLite amalgamation
    Fetching https://sqlite.org/2023/sqlite-autoconf-3420000.tar.gz
    Length: 3148813  SHA1: 036575929b174c1b829769255491ba2b32bda9ee  MD5: 0c5a92bc51cf07cae45b4a1e94653dea
    Checksums verified
    Running configure to work out SQLite compilation flags
./configure: 14090: test: xyes: unexpected operator
running build_ext
SQLite: Using amalgamation /tmp/apsw/sqlite3/sqlite3.c
SQLite: Using generated /tmp/apsw/sqlite3/sqlite3config.h
ICU: Added includes, flags and libraries from icu-config
building 'apsw.__init__' extension
creating build
creating build/temp.linux-x86_64-cpython-312
creating build/temp.linux-x86_64-cpython-312/src
x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -fPIC -DNDEBUG=1 -DAPSW_FORK_CHECKER=1 -DAPSW_USE_SQLITE_AMALGAMATION=1 -DAPSW_USE_SQLITE_CONFIG=1 -DSQLITE_ENABLE_FTS4=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_STAT4=1 -DSQLITE_ENABLE_JSON1=1 -DSQLITE_ENABLE_FTS5=1 -DSQLITE_ENABLE_RBU=1 -DSQLITE_ENABLE_GEOPOLY=1 -DSQLITE_ENABLE_MATH_FUNCTIONS=1 -DSQLITE_ENABLE_ICU=1 -DU_DISABLE_RENAMING=1 -DSQLITE_ENABLE_COLUMN_METADATA=1 -I/tmp/apsw/sqlite3 -Isrc -I/usr/include -I/tmp/apsw/.venv/include -I/usr/include/python3.12 -c src/apsw.c -o build/temp.linux-x86_64-cpython-312/src/apsw.o
In file included from src/apsw.c:81:
/tmp/apsw/sqlite3/sqlite3.c: In function ‘sqlite3DbMaskAllZero’:
/tmp/apsw/sqlite3/sqlite3.c:118300:13: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
118300 |   for(i=0; i<sizeof(yDbMask); i++) if( m[i] ) return 0;
       |             ^
In file included from /usr/include/python3.12/Python.h:12,
                 from src/apsw.c:110:
/usr/include/python3.12/pyconfig.h: At top level:
/usr/include/python3.12/pyconfig.h:352: warning: "HAVE_FCHMOD" redefined
  352 | #define HAVE_FCHMOD 1
      | 
/tmp/apsw/sqlite3/sqlite3.c:37386: note: this is the location of the previous definition
37386 | #  define HAVE_FCHMOD
      | 
creating build/lib.linux-x86_64-cpython-312
creating build/lib.linux-x86_64-cpython-312/apsw
x86_64-pc-linux-gnu-gcc -shared build/temp.linux-x86_64-cpython-312/src/apsw.o -L/usr/lib64 -L/usr/lib64 -licui18n -licuuc -licudata -o build/lib.linux-x86_64-cpython-312/apsw/__init__.cpython-312-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-312/apsw/__init__.cpython-312-x86_64-linux-gnu.so -> apsw
env python3 -m apsw.tests
                Python  /tmp/apsw/.venv/bin/python3 sys.version_info(major=3, minor=12, micro=0, releaselevel='beta', serial=1)
Testing with APSW file  /tmp/apsw/apsw/__init__.cpython-312-x86_64-linux-gnu.so
          APSW version  3.42.0.0
    SQLite lib version  3.42.0
SQLite headers version  3042000
    Using amalgamation  True
Not doing LoadExtension test.  You need to compile the extension first

  python3 setup.py build_test_extension
...........................................................A message about RecursionError is possible, and what is being tested
.................................................F........./usr/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=26759) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
.
======================================================================
FAIL: testVTableStuff (__main__.APSW.testVTableStuff)
Test new stuff added for Virtual tables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/apsw/apsw/tests.py", line 1643, in testVTableStuff
    self.assertRaisesUnraisable(TypeError, self.db.execute, "create table sptest_bam2(x)")
  File "/tmp/apsw/apsw/tests.py", line 372, in assertRaisesUnraisable
    return self.baseAssertRaisesUnraisable(True, exc, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/apsw/apsw/tests.py", line 416, in baseAssertRaisesUnraisable
    self.assertIsInstance(called[0][1], exc)  # check it was the correct type
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: UnicodeDecodeError('utf-8', b'\xff\xff\xff\xff', 0, 1, 'invalid start byte') is not an instance of <class 'TypeError'>

----------------------------------------------------------------------
Ran 119 tests in 28.522s

FAILED (failures=1)
make: *** [Makefile:110: test] Error 1
```

**Comment by rogerbinns** [comment]
I'll have to suppress the fork warning.  It is deliberately forking in order to [test the fork checker](https://rogerbinns.github.io/apsw/apsw.html#apsw.fork_checker).

The Unicode error is something I looked at yesterday.  It is new in 3.12 beta 1 and was not present in previous 3.12 alpha releases.  To my best determination it is actually a new bug in Python happening during [this code path](https://github.com/rogerbinns/apsw/blob/master/src/vtable.c#L2729).  I am going to wait till the next beta before spending more time digging.

**Comment by mgorny** [comment]
For the record, I'm testing on top of today's CPython 3.12 branch, so it's still present as of today.

**Comment by rogerbinns** [comment]
Next beta came out, and it was entirely my fault.

**Comment by mgorny** [comment]
Thanks for the fix!
